/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CompressRouteImport } from './routes/compress'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EmailRouteImport } from './routes/email'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowToCompressRouteImport } from './routes/how-to-compress'
import { Route as HowToMergeRouteImport } from './routes/how-to-merge'
import { Route as HowToSplitRouteImport } from './routes/how-to-split'
import { Route as MergeRouteImport } from './routes/merge'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SplitRouteImport } from './routes/split'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as WhatsappRouteImport } from './routes/whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressRoute = CompressRouteImport.update({
  id: '/compress',
  path: '/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToCompressRoute = HowToCompressRouteImport.update({
  id: '/how-to-compress',
  path: '/how-to-compress',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToMergeRoute = HowToMergeRouteImport.update({
  id: '/how-to-merge',
  path: '/how-to-merge',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToSplitRoute = HowToSplitRouteImport.update({
  id: '/how-to-split',
  path: '/how-to-split',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeRoute = MergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitRoute = SplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compress': typeof CompressRoute
  '/contact': typeof ContactRoute
  '/email': typeof EmailRoute
  '/faq': typeof FaqRoute
  '/how-to-compress': typeof HowToCompressRoute
  '/how-to-merge': typeof HowToMergeRoute
  '/how-to-split': typeof HowToSplitRoute
  '/merge': typeof MergeRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/split': typeof SplitRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compress': typeof CompressRoute
  '/contact': typeof ContactRoute
  '/email': typeof EmailRoute
  '/faq': typeof FaqRoute
  '/how-to-compress': typeof HowToCompressRoute
  '/how-to-merge': typeof HowToMergeRoute
  '/how-to-split': typeof HowToSplitRoute
  '/merge': typeof MergeRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/split': typeof SplitRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compress': typeof CompressRoute
  '/contact': typeof ContactRoute
  '/email': typeof EmailRoute
  '/faq': typeof FaqRoute
  '/how-to-compress': typeof HowToCompressRoute
  '/how-to-merge': typeof HowToMergeRoute
  '/how-to-split': typeof HowToSplitRoute
  '/merge': typeof MergeRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/split': typeof SplitRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compress'
    | '/contact'
    | '/email'
    | '/faq'
    | '/how-to-compress'
    | '/how-to-merge'
    | '/how-to-split'
    | '/merge'
    | '/privacy'
    | '/scan'
    | '/split'
    | '/terms'
    | '/use-cases'
    | '/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compress'
    | '/contact'
    | '/email'
    | '/faq'
    | '/how-to-compress'
    | '/how-to-merge'
    | '/how-to-split'
    | '/merge'
    | '/privacy'
    | '/scan'
    | '/split'
    | '/terms'
    | '/use-cases'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compress'
    | '/contact'
    | '/email'
    | '/faq'
    | '/how-to-compress'
    | '/how-to-merge'
    | '/how-to-split'
    | '/merge'
    | '/privacy'
    | '/scan'
    | '/split'
    | '/terms'
    | '/use-cases'
    | '/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompressRoute: typeof CompressRoute
  ContactRoute: typeof ContactRoute
  EmailRoute: typeof EmailRoute
  FaqRoute: typeof FaqRoute
  HowToCompressRoute: typeof HowToCompressRoute
  HowToMergeRoute: typeof HowToMergeRoute
  HowToSplitRoute: typeof HowToSplitRoute
  MergeRoute: typeof MergeRoute
  PrivacyRoute: typeof PrivacyRoute
  ScanRoute: typeof ScanRoute
  SplitRoute: typeof SplitRoute
  TermsRoute: typeof TermsRoute
  UseCasesRoute: typeof UseCasesRoute
  WhatsappRoute: typeof WhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress': {
      id: '/compress'
      path: '/compress'
      fullPath: '/compress'
      preLoaderRoute: typeof CompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-compress': {
      id: '/how-to-compress'
      path: '/how-to-compress'
      fullPath: '/how-to-compress'
      preLoaderRoute: typeof HowToCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-merge': {
      id: '/how-to-merge'
      path: '/how-to-merge'
      fullPath: '/how-to-merge'
      preLoaderRoute: typeof HowToMergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-split': {
      id: '/how-to-split'
      path: '/how-to-split'
      fullPath: '/how-to-split'
      preLoaderRoute: typeof HowToSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge': {
      id: '/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof MergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split': {
      id: '/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompressRoute: CompressRoute,
  ContactRoute: ContactRoute,
  EmailRoute: EmailRoute,
  FaqRoute: FaqRoute,
  HowToCompressRoute: HowToCompressRoute,
  HowToMergeRoute: HowToMergeRoute,
  HowToSplitRoute: HowToSplitRoute,
  MergeRoute: MergeRoute,
  PrivacyRoute: PrivacyRoute,
  ScanRoute: ScanRoute,
  SplitRoute: SplitRoute,
  TermsRoute: TermsRoute,
  UseCasesRoute: UseCasesRoute,
  WhatsappRoute: WhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
